{{- range $dataStoreID, $dataStore := .Values.dataStores }}

{{- $replicas := $.Values.dataStoreDefaults.replicas }}
{{- $clusterDomain := "cluster.local" }}

---
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: {{ $dataStoreID }}
  labels:
    etcd-operator.cozystack.io/cluster: {{ $dataStoreID | quote }}
spec:
  driver: etcd
  endpoints:
  - {{ printf "%s.%s.svc.%s:2379" $dataStoreID $.Release.Namespace $clusterDomain }}
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: etcd-ca-{{ $dataStoreID }}
          namespace: {{ $.Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: etcd-ca-{{ $dataStoreID }}
          namespace: {{ $.Release.Namespace }}
    clientCertificate:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: etcd-client-{{ $dataStoreID }}
          namespace: {{ $.Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: etcd-client-{{ $dataStoreID }}
          namespace: {{ $.Release.Namespace }}

{{- end }}