{{- range $dataStoreID, $dataStore := .Values.dataStores }}

---
# https://github.com/cozystack/etcd-operator/blob/main/charts/etcd-operator/crd-bases/etcd-operator.cozystack.io_etcdclusters.yaml
apiVersion: etcd-operator.cozystack.io/v1alpha2
kind: EtcdCluster
metadata:
  name: {{ $dataStoreID }}
  labels:
    etcd-operator.cozystack.io/cluster: {{ $dataStoreID | quote }}
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: {{ $dataStoreID }}
            topologyKey: kubernetes.io/hostname
          weight: 1
  replicas: {{ $.Values.dataStoreDefaults.replicas }}
  options:
    quotaBackendBytes: {{ mul (atoi (trimSuffix "Gi" ($dataStore.storage | default $.Values.dataStoreDefaults.storage))) 1024 1024 1024 }}
  storage:
    size: {{ $dataStore.storage | default $.Values.dataStoreDefaults.storage }}
    {{- if $dataStore.storageClassName }}
    storageClassName: {{ $dataStore.storageClassName }}
    {{- end }}
  tls:
    client:
      operatorClientSecretRef:
        name: etcd-client-{{ $dataStoreID }}
      serverSecretRef:
        name: etcd-server-{{ $dataStoreID }}
    peer:
      secretRef:
        name: etcd-peer-{{ $dataStoreID }}
  version: {{ $dataStore.version | required "[dataStore].version can't be empty." }}
{{- end }}