apiVersion: v2
name: superphenix-system
description: Helm chart to install Superphenix system on workload, storage, and management clusters
type: application
# This chart inherits the tag of the Git repository
version: 0.0.0
appVersion: "0.0.0"
