apiVersion: v2
name: superphenix-operator
description: A Helm chart for the Superphenix Operator
type: application
# This chart inherits the tag of the Git repository
version: 0.0.0
appVersion: "0.0.0"
