{{- range $preID, $cluster := .Values.clusters }}
{{- if eq $cluster.location $.Values.location }}

{{- $dataStore := ($cluster.controlPlane).dataStore | default dict }}
{{- if $dataStore.dedicated }}

{{- $projectID := $.Values.projectID -}}
{{- $clusterID := include "sfs-kaas.spxEID" (dict "project" $projectID "localID" $preID) }}
{{- $dataStoreID := printf "etcd-%s" $clusterID }}
{{- $dataStoreDefaults := $.Values.dataStoreDefaults -}}
{{- $replicas := $dataStoreDefaults.replicas }}
{{- $clusterDomain := $dataStoreDefaults.clusterDomain }}

---
# EtcdCluster: https://github.com/cozystack/etcd-operator/blob/main/charts/etcd-operator/crd-bases/etcd-operator.cozystack.io_etcdclusters.yaml
# Kamaji certs: https://github.com/clastix/kamaji-etcd/tree/master/charts/kamaji-etcd/templates
apiVersion: etcd-operator.cozystack.io/v1alpha2
kind: EtcdCluster
metadata:
  name: {{ $dataStoreID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  additionalMetadata:
    annotations:
      ovn.kubernetes.io/logical_router: ovn-cluster
      ovn.kubernetes.io/logical_switch: ovn-default
    labels:
      # don't include selector labels as they conflict with those set by etcd-operator
      superphenix.net/gitops: {{ $.Values.gitops | quote }}
      superphenix.net/organizationID: spx-{{ $.Values.organizationID }}
      superphenix.net/projectID: spx-{{ $.Values.projectID }}
      {{- if $.Values.gitops }}
      superphenix.net/organizationName: {{ $.Values.organizationName | quote }}
      superphenix.net/projectName: {{ $.Values.projectName | quote }}
      {{- end }}
      superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
      superphenix.net/resourceLocalID: {{ $preID | quote }}
      superphenix.net/resourceName: {{ $preID | quote }}
      superphenix.net/ignoreNetworkPolicies: "true"
      superphenix.net/workloadClass: kaas-datastore
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: {{ $dataStoreID }}
            topologyKey: kubernetes.io/hostname
          weight: 1
  replicas: {{ $replicas }}
  options:
    autoCompactionMode: periodic
    autoCompactionRetention: 5m
    # limit DB size to 85% of the PVC, leaving space for other files and some headroom in case of a full DB causing issues
    quotaBackendBytes: {{ int (mulf (atoi (trimSuffix "Gi" ($dataStore.storage | default $.Values.dataStoreDefaults.storage))) 1024 1024 1024 0.85) }}
    snapshotCount: 10000
  storage:
    size: {{ $dataStore.storage | default $dataStoreDefaults.storage }}
    storageClassName: {{ get $.Values.storageClassMapping (required "Must provide a storage class for the dedicated datastore." $dataStore.storageClassName )}}
  tls:
    client:
      operatorClientSecretRef:
        name: etcd-client-{{ $clusterID }}
      serverSecretRef:
        name: etcd-server-{{ $clusterID }}
    peer:
      secretRef:
        name: etcd-peer-{{ $clusterID }}
  version: {{ $dataStore.version | default $dataStoreDefaults.version }}

---
apiVersion: kamaji.clastix.io/v1alpha1
kind: DataStore
metadata:
  name: {{ $dataStoreID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
spec:
  driver: etcd
  endpoints:
    - {{ printf "%s.%s.svc.%s:2379" $dataStoreID $.Release.Namespace $clusterDomain }}
  tlsConfig:
    certificateAuthority:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: etcd-ca-{{ $clusterID }}
          namespace: {{ $.Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: etcd-ca-{{ $clusterID }}
          namespace: {{ $.Release.Namespace }}
    clientCertificate:
      certificate:
        secretReference:
          keyPath: tls.crt
          name: etcd-client-{{ $clusterID }}
          namespace: {{ $.Release.Namespace }}
      privateKey:
        secretReference:
          keyPath: tls.key
          name: etcd-client-{{ $clusterID }}
          namespace: {{ $.Release.Namespace }}

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd-ca-issuer-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-ca-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  isCA: true
  usages:
  - "signing"
  - "key encipherment"
  - "cert sign"
  commonName: etcd-ca
  secretName: etcd-ca-{{ $clusterID }}
  secretTemplate:
    labels:
      {{- include "sfs-kaas.labels" $ | nindent 6 }}
      superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
      superphenix.net/resourceLocalID: {{ $preID | quote }}
      superphenix.net/resourceName: {{ $preID | quote }}
  privateKey:
    algorithm: RSA
    size: 4096
  duration: 87600h # 10 years
  renewBefore: 960h0m0s # 40 days
  issuerRef:
    name: etcd-ca-issuer-{{ $clusterID }}
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd-issuer-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  ca:
    secretName: etcd-ca-{{ $clusterID }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-server-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  secretName: etcd-server-{{ $clusterID }}
  secretTemplate:
    labels:
      {{- include "sfs-kaas.labels" $ | nindent 6 }}
      superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
      superphenix.net/resourceLocalID: {{ $preID | quote }}
      superphenix.net/resourceName: {{ $preID | quote }}
  isCA: false
  usages:
    - "client auth"
    - "server auth"
    - "signing"
    - "key encipherment"
  dnsNames:
    - "{{ printf "*.%s-headless.%s.svc" $dataStoreID $.Release.Namespace }}"
    - "{{ printf "*.%s-headless.%s.svc.%s" $dataStoreID $.Release.Namespace $clusterDomain }}"
    - "{{ printf "*.%s.%s.svc" $dataStoreID $.Release.Namespace }}"
    - "{{ printf "*.%s.%s.svc.%s" $dataStoreID $.Release.Namespace $clusterDomain }}"
    - "{{ printf "%s.%s.svc" $dataStoreID $.Release.Namespace }}"
    - "{{ printf "%s.%s.svc.%s" $dataStoreID $.Release.Namespace $clusterDomain }}"
    - localhost
  ipAddresses:
    - 127.0.0.1
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  duration: 2160h0m0s # 3 months
  renewBefore: 336h0m0s # 14 days
  issuerRef:
    name: etcd-issuer-{{ $clusterID }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  secretName: etcd-peer-{{ $clusterID }}
  secretTemplate:
    labels:
      {{- include "sfs-kaas.labels" $ | nindent 6 }}
      superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
      superphenix.net/resourceLocalID: {{ $preID | quote }}
      superphenix.net/resourceName: {{ $preID | quote }}
  isCA: false
  usages:
    - "server auth"
    - "client auth"
    - "signing"
    - "key encipherment"
  dnsNames:
    - "{{ printf "*.%s-headless.%s.svc" $dataStoreID $.Release.Namespace }}"
    - "{{ printf "*.%s-headless.%s.svc.%s" $dataStoreID $.Release.Namespace $clusterDomain }}"
    - "{{ printf "*.%s.%s.svc" $dataStoreID $.Release.Namespace }}"
    - "{{ printf "*.%s.%s.svc.%s" $dataStoreID $.Release.Namespace $clusterDomain }}"
    - "{{ printf "%s.%s.svc" $dataStoreID $.Release.Namespace }}"
    - "{{ printf "%s.%s.svc.%s" $dataStoreID $.Release.Namespace $clusterDomain }}"
    - localhost
  ipAddresses:
    - 127.0.0.1
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  duration: 2160h0m0s # 3 months
  renewBefore: 336h0m0s # 14 days
  issuerRef:
    name: etcd-issuer-{{ $clusterID }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $preID | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  commonName: root
  secretName: etcd-client-{{ $clusterID }}
  secretTemplate:
    labels:
      {{- include "sfs-kaas.labels" $ | nindent 6 }}
      superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
      superphenix.net/resourceLocalID: {{ $preID | quote }}
      superphenix.net/resourceName: {{ $preID | quote }}
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  duration: 2160h0m0s # 3 months
  renewBefore: 336h0m0s # 14 days
  issuerRef:
    name: etcd-issuer-{{ $clusterID }}
    kind: Issuer

{{- end }}
{{- end }}
{{- end }}