{{- range $preID, $cluster := .Values.clusters }}
{{- if eq $cluster.location $.Values.location }}

{{- if hasKey $cluster "postInstallChart" }}

{{- $projectID := $.Values.projectID -}}
{{- $controlPlane := $cluster.controlPlane -}}
{{- $controlPlaneDefaults := $.Values.clusterDefaults.controlPlane -}}
{{- $clusterID := include "sfs-kaas.spxEID" (dict "project" $projectID "localID" $preID) }}
{{- $fqdn := ($controlPlane.network).fqdn | default (include "sfs-kaas.fqdn" (dict "root" $ "name" $clusterID)) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-install-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $cluster.name | quote }}
data:
  script.sh: |-
    #!/bin/bash
    # This script installs a user-defined chart in the tenant cluster

    sed "s/10.96.0.1/{{ $fqdn }}/" /job/kubeconfig > /var/run/kubeconfig

    echo -e "[+] Target cluster:\n\tID: {{ $clusterID }}\n\tName: {{ $cluster.name }}"
    echo "[+] Checking if TCP is ready."
    curl -kf https://{{ $fqdn }}:{{ $controlPlaneDefaults.network.apiServer.port }}/version -o /dev/null
    while [ $? != 0 ]
    do
      echo "[+] Waiting 120s for TCP to be ready."
      sleep 120
      echo "[+] Checking if TCP is ready."
      curl -kf https://{{ $fqdn }}:{{ $controlPlaneDefaults.network.apiServer.port }}/version -o /dev/null
    done

    echo "[+] Running helm upgrade."
    helm upgrade --install {{ $cluster.postInstallChart.chartName }} \
      {{- if regexMatch "^oci" $cluster.postInstallChart.repoUrl }}
      {{ $cluster.postInstallChart.repoUrl }}/{{ $cluster.postInstallChart.chartName }} \
      {{- else }}
      {{ $cluster.postInstallChart.chartName }} \
      --repo {{ $cluster.postInstallChart.repoUrl }} \
      {{- end }}
      --version {{ $cluster.postInstallChart.chartVersion }} \
      --namespace {{ $cluster.postInstallChart.namespace | default "default" }} \
      --create-namespace \
      --kubeconfig /var/run/kubeconfig \
      -f /job/values/values.yaml
    if [ $? -eq 0 ]; then
      echo "[+] Helm upgrade successful."
      exit 0
    else
      echo "[!] Helm upgrade failed."
      exit 1
    fi

  values.yaml: |-
    # Values passed to the user-defined chart
    # defined under clusters.<cluster>.postInstallChart.values

    {{- if hasKey $cluster.postInstallChart "values" }}
    {{- $cluster.postInstallChart.values | toYaml | nindent 4 }}
    {{- end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-{{ $cluster.postInstallChart.revision | default 1 }}-{{ $clusterID }}
  labels:
    {{- include "sfs-kaas.labels" $ | nindent 4 }}
    superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
    superphenix.net/resourceLocalID: {{ $preID | quote }}
    superphenix.net/resourceName: {{ $cluster.name | quote }}
    superphenix.net/ignoreNetworkPolicies: "true"
    superphenix.net/workloadClass: kaas-essentials-job
spec:
  template:
    metadata:
      annotations:
        # We need to use a specialized network that is not restricted by client policies or lack of connectivity
        v1.multus-cni.io/default-network: kube-system/system-isolated-egress
      labels:
        {{- include "sfs-kaas.labels" $ | nindent 8 }}
        superphenix.net/resourceEffectiveID: {{ $clusterID | quote }}
        superphenix.net/resourceLocalID: {{ $preID | quote }}
        superphenix.net/resourceName: {{ $cluster.name | quote }}
        superphenix.net/generated: "true"
        superphenix.net/ignoreNetworkPolicies: "true"
        superphenix.net/workloadClass: kaas-essentials-job
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "alpine/helm:3.19"
          command: ["/job/script/script.sh"]
          volumeMounts:
            - name: script
              mountPath: /job/script
            - name: kubeconfig
              mountPath: /job
            - name: values
              mountPath: /job/values
      volumes:
        - name: script
          configMap:
            name: "post-install-{{ $clusterID }}"
            defaultMode: 0777
            items:
            - key: "script.sh"
              path: "script.sh"
        - name: kubeconfig
          secret:
            secretName: "{{ $clusterID }}-admin-kubeconfig"
            defaultMode: 0555
            items:
            - key: admin.conf
              path: kubeconfig
        - name: values
          configMap:
            name: "post-install-{{ $clusterID }}"
            defaultMode: 0555
            items:
            - key: "values.yaml"
              path: "values.yaml"

{{- end }}
{{- end }}
{{- end }}
