{{- range .Values.clusters }}
{{- $cluster := .name }}
{{- range .pools }}
{{- range .storageClasses }}
{{- if and .encryption .encryption.enabled (eq (.encryption.kmsType | default "metadata") "metadata") }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $scName := .fullName | default (printf "%s.%s" $cluster .name) }}
  name: {{ $scName }}-encryption
  namespace: {{ $cluster }}
stringData:
  encryptionPassphrase: {{ .encryption.passphrase | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
