apiVersion: v1
kind: ConfigMap
metadata:
  name: superphenix-mgmt-argocd-default-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superphenix-operator.labels" . | nindent 4 }}
data:
  values.yaml: |
    # Global ArgoCD configuration
    global:
      # Domain used for ingresses, certificates, SSO, notifications, etc.
      domain: argocd.example.com
      {{- if .Values.installOnClusterWithoutCNI }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoSchedule"
      hostAliases:
        - ip: "::"
          hostnames:
            - "superphenix-argocd-redis"
            - "superphenix-argocd-repo-server"
      {{- end }}

      # Restrict network flow in and out of ArgoCD
      networkPolicy:
        create: true

    # ArgoCD configuration
    configs:
      # ConfigMap configuration
      cm:
        # Permit using the shell from inside the ArgoCD interface
        exec.enabled: true

        # Generate status badges for applications
        statusbadge.enabled: true

        # Optimized tracking of the resources
        application.resourceTrackingMethod: annotation

        # We need this ID when tracking with annotations to distinguish between multiple ArgoCD instances
        # when one cluster is managed by multiple ArgoCDs
        installationID: "operator.superphenix.net"

        # Setup health assessment for Application CRDs to allow for sync waves between them
        resource.customizations: |
          argoproj.io/Application:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.health ~= nil then
                  hs.status = obj.status.health.status
                  if hs.status == "Progressing" then
                    hs.status = "Healthy"
                  end
                  if obj.status.health.message ~= nil then
                    hs.message = obj.status.health.message
                  end
                end
              end
              return hs
          networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
          Service:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs

      cmp:
        create: true
        plugins:
          uuidv5:
            init:
              command:
                - bash
                - "-c"
                - set -e && set -o pipefail && /clone.sh $ARGOCD_ENV_REPO
            generate:
              command:
                - bash
                - "-c"
                - set -e && set -o pipefail && helm template $ARGOCD_ENV_RELEASE --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_PARAMS} ${ARGOCD_ENV_HELM_VALUEFILES} -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | /parser.sh

      # Parameters injected to ArgoCD
      params:
        # The default behavior of the ApplicationSet controller is unsatisfactory when it comes to globbing, patch it
        # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git-File-Globbing/
        applicationsetcontroller.enable.new.git.file.globbing: "true"
        server.insecure: true
        # Authorize applications in any SPX project namespace
        application.namespaces: "spx-*"

      # Override ArgoCD style to differentiate this ArgoCD from others
      styles: |
        .sidebar {
          background-color: #000;
        }
        .sidebar__logo img {
            display: none;
        }
        .sidebar__version {
            display: none;
        }
        .sidebar__logo {
            background: url(https://docs.superphenix.net/assets/spx.svg);
            background-size: 80%;
            background-repeat: no-repeat;
            padding-left: 1rem !important;
            margin-left: 10px !important;
            filter: invert(1);
        }

    controller:
      {{- if .Values.installOnClusterWithoutCNI }}
      hostNetwork: true
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: superphenix-argocd
                app.kubernetes.io/managed-by: Helm
            topologyKey: kubernetes.io/hostname
      {{- end }}
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          # ArgoCD will fail to sync if it's installing an instance of ArgoCD
          # before the Prometheus ServiceMonitor CRD is installed on the cluster
          # We simply skip the dry-run in that case
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

    dex:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          # ArgoCD will fail to sync if it's installing an instance of ArgoCD
          # before the Prometheus ServiceMonitor CRD is installed on the cluster
          # We simply skip the dry-run in that case
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

    server:
      {{- if .Values.installOnClusterWithoutCNI }}
      hostNetwork: true
      # We need to avoid conflicts with other resources listening on port 8080
      # That's why we set it to 8888
      containerPorts:
        server: 8888
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: superphenix-argocd
                app.kubernetes.io/managed-by: Helm
            topologyKey: kubernetes.io/hostname
      {{- end }}
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          # ArgoCD will fail to sync if it's installing an instance of ArgoCD
          # before the Prometheus ServiceMonitor CRD is installed on the cluster
          # We simply skip the dry-run in that case
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      ingress:
        enabled: true
        hostname: "argocd.superphenix.net"
        tls: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.entrypoints: websecure

    repoServer:
      {{- if .Values.installOnClusterWithoutCNI }}
      hostNetwork: true
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: superphenix-argocd
                app.kubernetes.io/managed-by: Helm
            topologyKey: kubernetes.io/hostname
      {{- end }}
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          # ArgoCD will fail to sync if it's installing an instance of ArgoCD
          # before the Prometheus ServiceMonitor CRD is installed on the cluster
          # We simply skip the dry-run in that case
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      extraContainers:
        - name: cmp-uuidv5
          image: ghcr.io/super-phenix/uuidv5:latest
          imagePullPolicy: IfNotPresent
          args:
            - "/var/run/argocd/argocd-cmp-server"
            - "--loglevel=debug"
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: uuidv5.yaml
              name: argocd-cmp-cm
            - mountPath: /tmp
              name: cmp-tmp
      volumes:
        - name: argocd-cmp-cm
          configMap:
            name: argocd-cmp-cm
        - name: cmp-tmp
          emptyDir: {}

    redis:
      {{- if .Values.installOnClusterWithoutCNI }}
      hostNetwork: true
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: superphenix-argocd
                app.kubernetes.io/managed-by: Helm
            topologyKey: kubernetes.io/hostname
      {{- end }}

    {{- if .Values.installOnClusterWithoutCNI }}
    redisSecretInit:
      hostNetwork: true
    {{- end }}

    applicationSet:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          # ArgoCD will fail to sync if it's installing an instance of ArgoCD
          # before the Prometheus ServiceMonitor CRD is installed on the cluster
          # We simply skip the dry-run in that case
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

    notifications:
      enabled: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: superphenix-mgmt-argocd-ha-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superphenix-operator.labels" . | nindent 4 }}
data:
  values.yaml: |
    controller:
      dynamicClusterDistribution: true
    server:
      autoscaling:
        enabled: true
    repoServer:
      autoscaling:
        enabled: true
    redis-ha:
      enabled: true
      exporter:
        enabled: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          # ArgoCD will fail to sync if it's installing an instance of ArgoCD
          # before the Prometheus ServiceMonitor CRD is installed on the cluster
          # We simply skip the dry-run in that case
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
