apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "superphenix-operator.fullname" . }}-manager-role
  labels:
    {{- include "superphenix-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
m      - configmaps
      - namespaces
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.superphenix.net
    resources:
      - clusters
      - organizations
      - projects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.superphenix.net
    resources:
      - clusters/finalizers
      - organizations/finalizers
      - projects/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.superphenix.net
    resources:
      - clusters/status
      - organizations/status
      - projects/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "superphenix-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "superphenix-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "superphenix-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "superphenix-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
