apiVersion: v1
kind: Service
metadata:
  name: {{ include "superphenix-api.fullname" . }}
  labels:
    {{- include "superphenix-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 7000
      targetPort: admin-http
      protocol: TCP
      name: admin-http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "superphenix-api.selectorLabels" . | nindent 4 }}
