{{ $cluster := .Values.cluster }}
{{ $argocd := .Values.argocd }}
{{ $disableAll := .Values.disableAll }}
{{ $forceManual := .Values.forceManual }}
{{ $labels := include "superphenix-system.labels" . }}

{{- $currentMode := .Values.cluster.deploymentTopology }}
{{- if eq .Values.cluster.type "Management" }}
  {{- $currentMode = "Management" }}
{{- else if eq .Values.cluster.deploymentTopology "Decoupled" }}
  {{- $currentMode = printf "%s%s" .Values.cluster.deploymentTopology .Values.cluster.type }}
{{- end }}

{{- range $app, $values := .Values.apps }}
{{- $shouldDeploy := false }}
{{- if and (eq $values.enabled true) (eq $disableAll false) }}
  {{- if eq $currentMode "Management" }}
    {{- if has "Management" (default (list) $values.modes) }}
      {{- $shouldDeploy = true }}
    {{- end }}
  {{- else }}
    {{- if or (not $values.modes) (has $currentMode (default (list) $values.modes)) }}
      {{- $shouldDeploy = true }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if $shouldDeploy }}

---
apiVersion: {{ $argocd.appVersion }}
kind: Application
metadata:
  name: {{ $cluster.name }}-{{ $app | lower }}
  namespace: {{ $argocd.namespace }}
  {{- $cleanup := or $.Values.cleanupOnDeletion (default false $values.automation.cleanupOnDeletion) }}
  {{- if $cleanup }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
  labels:
    operator.superphenix.net/clusterName: {{ $cluster.name }}
    operator.superphenix.net/application: {{ $app | lower }}
    operator.superphenix.net/managed: "true"
    {{ $labels | nindent 4 }}
  annotations:
    {{- if hasKey $values "wave" }}
    argocd.argoproj.io/sync-wave: {{ $values.wave | quote }}
    {{- end }}
spec:
  project: {{ $argocd.project }}
  source:
    repoURL: {{ $values.repoURL | quote }}

    {{- with $values.helm }}
    {{- with .chart }}
    chart: {{ . | quote }}
    {{- end }}
    {{- end }}

    {{- with $values.path }}
    path: {{ . | quote }}
    {{- end }}

    {{- with $values.directory }}
    directory:
      {{- with .recurse }}
      recurse: {{ . }}
      {{- end }}
    {{- end }}

    targetRevision: {{ $values.targetRevision | default $.Chart.AppVersion | quote }}

    {{- with $values.helm }}
    helm:
      {{- with .releaseName }}
      releaseName: {{ . | quote }}
      {{- end }}

      {{- with .values }}
      valuesObject:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    {{- end }}
  destination:
    name: {{ $cluster.name | quote }}
    namespace: {{ $values.namespace | default $.Release.Namespace | quote }}
  {{- with $values.ignoreDifferences }}
  ignoreDifferences:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
  syncPolicy:
    automated:
      {{- $syncEnabled := and $values.automation.enabled (not $forceManual) | default false }}
      enabled: {{ $syncEnabled }}
      {{- if $values.automation.selfHeal }}
      selfHeal: true
      {{- end }}
      {{- if $values.automation.prune }}
      prune: true
      {{- end }}
    syncOptions:
      {{- if $values.automation.syncOptions }}
      {{- toYaml $values.automation.syncOptions | nindent 6 }}
      {{- end }}
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    managedNamespaceMetadata:
      labels:
        superphenix.net/gitops: "true"
        {{- with $values.nsLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
{{- end }}
{{- end }}

