{{ $cluster := .Values.cluster }}
{{ $argocd := .Values.argocd }}
{{ $disableAll := .Values.disableAll }}
{{ $forceManual := .Values.forceManual }}
{{ $labels := include "superphenix-system.labels" . }}

{{- range $app, $values := .Values.apps }}
{{- $currentMode := $.Values.cluster.deploymentTopology }}
{{- if eq $.Values.cluster.deploymentTopology "Decoupled" }}
{{- $currentMode = printf "%s%s" $.Values.cluster.deploymentTopology $.Values.cluster.type }}
{{- end }}
{{- if and (eq $values.enabled true) (eq $disableAll false) (has $currentMode (default (list) $values.modes)) }}

---
apiVersion: {{ $argocd.appVersion }}
kind: Application
metadata:
  name: {{ $cluster.name }}-{{ $app | lower }}
  namespace: {{ $argocd.namespace }}
  {{- if or $.Values.cleanupOnDeletion (default false $values.automation.cleanupOnDeletion) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
  labels:
    operator.superphenix.net/clusterName: {{ $cluster.name }}
    operator.superphenix.net/application: {{ $app | lower }}
    operator.superphenix.net/managed: "true"
    {{ $labels | nindent 4 }}
  annotations:
    {{- if hasKey $values "wave" }}
    argocd.argoproj.io/sync-wave: {{ $values.wave | quote }}
    {{- end }}
spec:
  project: {{ $argocd.project }}
  source:
    repoURL: {{ $values.repoURL | quote }}

    {{- with $values.helm }}
    {{- with .chart }}
    chart: {{ . | quote }}
    {{- end }}
    {{- end }}

    {{- with $values.path }}
    path: {{ . | quote }}
    {{- end }}

    {{- with $values.directory }}
    directory:
      {{- with .recurse }}
      recurse: {{ . }}
      {{- end }}
    {{- end }}

    targetRevision: {{ $values.targetRevision | default .Chart.AppVersion }}

    {{- with $values.helm }}
    helm:
      {{- with .releaseName }}
      releaseName: {{ . | quote }}
      {{- end }}

      {{- with .values }}
      valuesObject:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    {{- end }}
  destination:
    name: {{ $cluster.name | quote }}
    namespace: {{ $values.namespace | quote }}
  {{- with $values.ignoreDifferences }}
  ignoreDifferences:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
  syncPolicy:
    automated:
      enabled: {{ and $values.automation.enabled (not $forceManual) | default false }}
      {{- if $values.automation.selfHeal }}
      selfHeal: true
      {{- end }}
      {{- if $values.automation.prune }}
      prune: true
      {{- end }}
    syncOptions:
      {{- if $values.automation.syncOptions }}
      {{- toYaml $values.automation.syncOptions | nindent 6 }}
      {{- end }}
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    managedNamespaceMetadata:
      labels:
        superphenix.net/gitops: "true"
        {{- with $values.nsLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}

{{- end }}
{{- end }}

