// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://superphenix.net",
            "email": "contact@superphenix.net"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/{orgId}/{projectId}/argo": {
            "get": {
                "security": [
                    {
                        "Bearer": [
                            ""
                        ]
                    }
                ],
                "description": "List every argo apps for a project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1",
                    "Argo"
                ],
                "summary": "List Argo Apps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Applications",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/view.Application"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": [
                            ""
                        ]
                    }
                ],
                "description": "Create an Argo App",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1",
                    "Argo"
                ],
                "summary": "Create an Argo App",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Argo App",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/argoApp.CreateAppInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/{orgId}/{projectId}/argo/localId/{localId}": {
            "get": {
                "security": [
                    {
                        "Bearer": [
                            ""
                        ]
                    }
                ],
                "description": "Get Argo App by Local ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1",
                    "Argo"
                ],
                "summary": "Get Argo App by Local ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Local ID",
                        "name": "localId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Application",
                        "schema": {
                            "$ref": "#/definitions/view.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/{orgId}/{projectId}/argo/{effectiveId}": {
            "get": {
                "security": [
                    {
                        "Bearer": [
                            ""
                        ]
                    }
                ],
                "description": "Get Argo App by Effective ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1",
                    "Argo"
                ],
                "summary": "Get Argo App by Effective ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Effective ID",
                        "name": "effectiveId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Application",
                        "schema": {
                            "$ref": "#/definitions/view.Application"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": [
                            ""
                        ]
                    }
                ],
                "description": "Update Argo App",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1",
                    "Argo"
                ],
                "summary": "Update Argo App",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Effective ID",
                        "name": "effectiveId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Argo App",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/argoApp.UpdateAppInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": [
                            ""
                        ]
                    }
                ],
                "description": "Delete Argo App by Effective ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1",
                    "Argo"
                ],
                "summary": "Delete Argo App",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Effective ID",
                        "name": "effectiveId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/{orgId}/{projectId}/mark": {
            "get": {
                "security": [
                    {
                        "Bearer": [
                            ""
                        ]
                    }
                ],
                "description": "Mark all argo resources inside a project for deletion",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1",
                    "GC"
                ],
                "summary": "Mark for deletion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "argoApp.AppSource": {
            "type": "object",
            "properties": {
                "chart": {
                    "type": "string"
                },
                "helm": {
                    "$ref": "#/definitions/v1alpha1.ApplicationSourceHelm"
                },
                "path": {
                    "type": "string"
                },
                "plugin": {
                    "$ref": "#/definitions/v1alpha1.ApplicationSourcePlugin"
                },
                "repoUrl": {
                    "type": "string"
                },
                "targetRevision": {
                    "type": "string"
                }
            }
        },
        "argoApp.CreateAppInfo": {
            "type": "object",
            "properties": {
                "general": {
                    "type": "object",
                    "properties": {
                        "appName": {
                            "type": "string"
                        },
                        "destination": {
                            "type": "string"
                        }
                    }
                },
                "orgID": {
                    "type": "string"
                },
                "projectID": {
                    "type": "string"
                },
                "resourceEffectiveID": {
                    "type": "string"
                },
                "resourceLocalID": {
                    "type": "string"
                },
                "spec": {
                    "type": "object",
                    "properties": {
                        "ignoreDifferences": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1alpha1.ResourceIgnoreDifferences"
                            }
                        },
                        "source": {
                            "$ref": "#/definitions/argoApp.AppSource"
                        }
                    }
                }
            }
        },
        "argoApp.UpdateAppInfo": {
            "type": "object",
            "properties": {
                "ignoreDifferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.ResourceIgnoreDifferences"
                    }
                },
                "source": {
                    "$ref": "#/definitions/argoApp.AppSource"
                }
            }
        },
        "health.HealthStatusCode": {
            "type": "string",
            "enum": [
                "Unknown",
                "Progressing",
                "Healthy",
                "Suspended",
                "Degraded",
                "Missing"
            ],
            "x-enum-varnames": [
                "HealthStatusUnknown",
                "HealthStatusProgressing",
                "HealthStatusHealthy",
                "HealthStatusSuspended",
                "HealthStatusDegraded",
                "HealthStatusMissing"
            ]
        },
        "intstr.IntOrString": {
            "type": "object",
            "properties": {
                "intVal": {
                    "type": "integer"
                },
                "strVal": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/intstr.Type"
                }
            }
        },
        "intstr.Type": {
            "type": "integer",
            "format": "int64",
            "enum": [
                0,
                1
            ],
            "x-enum-comments": {
                "Int": "The IntOrString holds an int.",
                "String": "The IntOrString holds a string."
            },
            "x-enum-descriptions": [
                "The IntOrString holds an int.",
                "The IntOrString holds a string."
            ],
            "x-enum-varnames": [
                "Int",
                "String"
            ]
        },
        "runtime.RawExtension": {
            "type": "object"
        },
        "v1.Operation": {
            "type": "string",
            "enum": [
                "CREATE",
                "UPDATE",
                "DELETE",
                "CONNECT"
            ],
            "x-enum-varnames": [
                "Create",
                "Update",
                "Delete",
                "Connect"
            ]
        },
        "v1.OwnerReference": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "description": "API version of the referent.",
                    "type": "string"
                },
                "blockOwnerDeletion": {
                    "description": "If true, AND if the owner has the \"foregroundDeletion\" finalizer, then\nthe owner cannot be deleted from the key-value store until this\nreference is removed.\nSee https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion\nfor how the garbage collector interacts with this field and enforces the foreground deletion.\nDefaults to false.\nTo set this field, a user needs \"delete\" permission of the owner,\notherwise 422 (Unprocessable Entity) will be returned.\n+optional",
                    "type": "boolean"
                },
                "controller": {
                    "description": "If true, this reference points to the managing controller.\n+optional",
                    "type": "boolean"
                },
                "kind": {
                    "description": "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names",
                    "type": "string"
                },
                "uid": {
                    "description": "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids",
                    "type": "string"
                }
            }
        },
        "v1.ResourceHealth": {
            "type": "object",
            "properties": {
                "health": {
                    "description": "Health of the resource.\ncan be one of:\n - Healthy: operates as normal\n - Unhealthy: reported unhealthy. We consider this a temporary health issue\n              since we do not have a mechanism today to distinguish\n              temporary and permanent issues.\n - Unknown: The status cannot be determined.\n            For example, Device Plugin got unregistered and hasn't been re-registered since.\n\nIn future we may want to introduce the PermanentlyUnhealthy Status.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ResourceHealthStatus"
                        }
                    ]
                },
                "resourceID": {
                    "description": "ResourceID is the unique identifier of the resource. See the ResourceID type for more information.",
                    "type": "string"
                }
            }
        },
        "v1.ResourceHealthStatus": {
            "type": "string",
            "enum": [
                "Healthy",
                "Unhealthy",
                "Unknown"
            ],
            "x-enum-varnames": [
                "ResourceHealthStatusHealthy",
                "ResourceHealthStatusUnhealthy",
                "ResourceHealthStatusUnknown"
            ]
        },
        "v1.ResourceName": {
            "type": "string",
            "enum": [
                "cpu",
                "memory",
                "storage",
                "ephemeral-storage",
                "pods",
                "services",
                "replicationcontrollers",
                "resourcequotas",
                "secrets",
                "configmaps",
                "persistentvolumeclaims",
                "services.nodeports",
                "services.loadbalancers",
                "requests.cpu",
                "requests.memory",
                "requests.storage",
                "requests.ephemeral-storage",
                "limits.cpu",
                "limits.memory",
                "limits.ephemeral-storage"
            ],
            "x-enum-varnames": [
                "ResourceCPU",
                "ResourceMemory",
                "ResourceStorage",
                "ResourceEphemeralStorage",
                "ResourcePods",
                "ResourceServices",
                "ResourceReplicationControllers",
                "ResourceQuotas",
                "ResourceSecrets",
                "ResourceConfigMaps",
                "ResourcePersistentVolumeClaims",
                "ResourceServicesNodePorts",
                "ResourceServicesLoadBalancers",
                "ResourceRequestsCPU",
                "ResourceRequestsMemory",
                "ResourceRequestsStorage",
                "ResourceRequestsEphemeralStorage",
                "ResourceLimitsCPU",
                "ResourceLimitsMemory",
                "ResourceLimitsEphemeralStorage"
            ]
        },
        "v1.ResourceStatus": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the resource. Must be unique within the pod and in case of non-DRA resource, match one of the resources from the pod spec.\nFor DRA resources, the value must be \"claim:\u003cclaim_name\u003e/\u003crequest\u003e\".\nWhen this status is reported about a container, the \"claim_name\" and \"request\" must match one of the claims of this container.\n+required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.ResourceName"
                        }
                    ]
                },
                "resources": {
                    "description": "List of unique resources health. Each element in the list contains an unique resource ID and its health.\nAt a minimum, for the lifetime of a Pod, resource ID must uniquely identify the resource allocated to the Pod on the Node.\nIf other Pod on the same Node reports the status with the same resource ID, it must be the same resource they share.\nSee ResourceID type definition for a specific format it has in various use cases.\n+listType=map\n+listMapKey=resourceID",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ResourceHealth"
                    }
                }
            }
        },
        "v1alpha1.AppHealthStatus": {
            "type": "object",
            "properties": {
                "lastTransitionTime": {
                    "description": "LastTransitionTime is the time the HealthStatus was set or updated",
                    "type": "string"
                },
                "message": {
                    "description": "Message is a human-readable informational message describing the health status\n\nDeprecated: this field is not used and will be removed in a future release.",
                    "type": "string"
                },
                "status": {
                    "description": "Status holds the status code of the application",
                    "allOf": [
                        {
                            "$ref": "#/definitions/health.HealthStatusCode"
                        }
                    ]
                }
            }
        },
        "v1alpha1.ApplicationCondition": {
            "type": "object",
            "properties": {
                "lastTransitionTime": {
                    "description": "LastTransitionTime is the time the condition was last observed",
                    "type": "string"
                },
                "message": {
                    "description": "Message contains human-readable message indicating details about condition",
                    "type": "string"
                },
                "type": {
                    "description": "Type is an application condition type",
                    "type": "string"
                }
            }
        },
        "v1alpha1.ApplicationDestination": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name is an alternate way of specifying the target cluster by its symbolic name. This must be set if Server is not set.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace specifies the target namespace for the application's resources.\nThe namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace",
                    "type": "string"
                },
                "server": {
                    "description": "Server specifies the URL of the target cluster's Kubernetes control plane API. This must be set if Name is not set.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.ApplicationSource": {
            "type": "object",
            "properties": {
                "chart": {
                    "description": "Chart is a Helm chart name, and must be specified for applications sourced from a Helm repo.",
                    "type": "string"
                },
                "directory": {
                    "description": "Directory holds path/directory specific options",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSourceDirectory"
                        }
                    ]
                },
                "helm": {
                    "description": "Helm holds helm specific options",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSourceHelm"
                        }
                    ]
                },
                "kustomize": {
                    "description": "Kustomize holds kustomize specific options",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSourceKustomize"
                        }
                    ]
                },
                "name": {
                    "description": "Name is used to refer to a source and is displayed in the UI. It is used in multi-source Applications.",
                    "type": "string"
                },
                "path": {
                    "description": "Path is a directory path within the Git repository, and is only valid for applications sourced from Git.",
                    "type": "string"
                },
                "plugin": {
                    "description": "Plugin holds config management plugin specific options",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSourcePlugin"
                        }
                    ]
                },
                "ref": {
                    "description": "Ref is reference to another source within sources field. This field will not be used if used with a ` + "`" + `source` + "`" + ` tag.",
                    "type": "string"
                },
                "repoURL": {
                    "description": "RepoURL is the URL to the repository (Git or Helm) that contains the application manifests",
                    "type": "string"
                },
                "targetRevision": {
                    "description": "TargetRevision defines the revision of the source to sync the application to.\nIn case of Git, this can be commit, tag, or branch. If omitted, will equal to HEAD.\nIn case of Helm, this is a semver tag for the Chart's version.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.ApplicationSourceDirectory": {
            "type": "object",
            "properties": {
                "exclude": {
                    "description": "Exclude contains a glob pattern to match paths against that should be explicitly excluded from being used during manifest generation",
                    "type": "string"
                },
                "include": {
                    "description": "Include contains a glob pattern to match paths against that should be explicitly included during manifest generation",
                    "type": "string"
                },
                "jsonnet": {
                    "description": "Jsonnet holds options specific to Jsonnet",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSourceJsonnet"
                        }
                    ]
                },
                "recurse": {
                    "description": "Recurse specifies whether to scan a directory recursively for manifests",
                    "type": "boolean"
                }
            }
        },
        "v1alpha1.ApplicationSourceHelm": {
            "type": "object",
            "properties": {
                "apiVersions": {
                    "description": "APIVersions specifies the Kubernetes resource API versions to pass to Helm when templating manifests. By default,\nArgo CD uses the API versions of the target cluster. The format is [group/]version/kind.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fileParameters": {
                    "description": "FileParameters are file parameters to the helm template",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.HelmFileParameter"
                    }
                },
                "ignoreMissingValueFiles": {
                    "description": "IgnoreMissingValueFiles prevents helm template from failing when valueFiles do not exist locally by not appending them to helm template --values",
                    "type": "boolean"
                },
                "kubeVersion": {
                    "description": "KubeVersion specifies the Kubernetes API version to pass to Helm when templating manifests. By default, Argo CD\nuses the Kubernetes version of the target cluster.",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace is an optional namespace to template with. If left empty, defaults to the app's destination namespace.",
                    "type": "string"
                },
                "parameters": {
                    "description": "Parameters is a list of Helm parameters which are passed to the helm template command upon manifest generation",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.HelmParameter"
                    }
                },
                "passCredentials": {
                    "description": "PassCredentials pass credentials to all domains (Helm's --pass-credentials)",
                    "type": "boolean"
                },
                "releaseName": {
                    "description": "ReleaseName is the Helm release name to use. If omitted it will use the application name",
                    "type": "string"
                },
                "skipCrds": {
                    "description": "SkipCrds skips custom resource definition installation step (Helm's --skip-crds)",
                    "type": "boolean"
                },
                "skipSchemaValidation": {
                    "description": "SkipSchemaValidation skips JSON schema validation (Helm's --skip-schema-validation)",
                    "type": "boolean"
                },
                "skipTests": {
                    "description": "SkipTests skips test manifest installation step (Helm's --skip-tests).",
                    "type": "boolean"
                },
                "valueFiles": {
                    "description": "ValuesFiles is a list of Helm value files to use when generating a template",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "values": {
                    "description": "Values specifies Helm values to be passed to helm template, typically defined as a block. ValuesObject takes precedence over Values, so use one or the other.\n+patchStrategy=replace",
                    "type": "string"
                },
                "valuesObject": {
                    "description": "ValuesObject specifies Helm values to be passed to helm template, defined as a map. This takes precedence over Values.\n+kubebuilder:pruning:PreserveUnknownFields",
                    "allOf": [
                        {
                            "$ref": "#/definitions/runtime.RawExtension"
                        }
                    ]
                },
                "version": {
                    "description": "Version is the Helm version to use for templating (\"3\")",
                    "type": "string"
                }
            }
        },
        "v1alpha1.ApplicationSourceJsonnet": {
            "type": "object",
            "properties": {
                "extVars": {
                    "description": "ExtVars is a list of Jsonnet External Variables",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.JsonnetVar"
                    }
                },
                "libs": {
                    "description": "Additional library search dirs",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tlas": {
                    "description": "TLAS is a list of Jsonnet Top-level Arguments",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.JsonnetVar"
                    }
                }
            }
        },
        "v1alpha1.ApplicationSourceKustomize": {
            "type": "object",
            "properties": {
                "apiVersions": {
                    "description": "APIVersions specifies the Kubernetes resource API versions to pass to Helm when templating manifests. By default,\nArgo CD uses the API versions of the target cluster. The format is [group/]version/kind.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "commonAnnotations": {
                    "description": "CommonAnnotations is a list of additional annotations to add to rendered manifests",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "commonAnnotationsEnvsubst": {
                    "description": "CommonAnnotationsEnvsubst specifies whether to apply env variables substitution for annotation values",
                    "type": "boolean"
                },
                "commonLabels": {
                    "description": "CommonLabels is a list of additional labels to add to rendered manifests",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "components": {
                    "description": "Components specifies a list of kustomize components to add to the kustomization before building",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "forceCommonAnnotations": {
                    "description": "ForceCommonAnnotations specifies whether to force applying common annotations to resources for Kustomize apps",
                    "type": "boolean"
                },
                "forceCommonLabels": {
                    "description": "ForceCommonLabels specifies whether to force applying common labels to resources for Kustomize apps",
                    "type": "boolean"
                },
                "ignoreMissingComponents": {
                    "description": "IgnoreMissingComponents prevents kustomize from failing when components do not exist locally by not appending them to kustomization file",
                    "type": "boolean"
                },
                "images": {
                    "description": "Images is a list of Kustomize image override specifications",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "kubeVersion": {
                    "description": "KubeVersion specifies the Kubernetes API version to pass to Helm when templating manifests. By default, Argo CD\nuses the Kubernetes version of the target cluster.",
                    "type": "string"
                },
                "labelIncludeTemplates": {
                    "description": "LabelIncludeTemplates specifies whether to apply common labels to resource templates or not",
                    "type": "boolean"
                },
                "labelWithoutSelector": {
                    "description": "LabelWithoutSelector specifies whether to apply common labels to resource selectors or not",
                    "type": "boolean"
                },
                "namePrefix": {
                    "description": "NamePrefix is a prefix appended to resources for Kustomize apps",
                    "type": "string"
                },
                "nameSuffix": {
                    "description": "NameSuffix is a suffix appended to resources for Kustomize apps",
                    "type": "string"
                },
                "namespace": {
                    "description": "Namespace sets the namespace that Kustomize adds to all resources",
                    "type": "string"
                },
                "patches": {
                    "description": "Patches is a list of Kustomize patches",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.KustomizePatch"
                    }
                },
                "replicas": {
                    "description": "Replicas is a list of Kustomize Replicas override specifications",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.KustomizeReplica"
                    }
                },
                "version": {
                    "description": "Version controls which version of Kustomize to use for rendering manifests",
                    "type": "string"
                }
            }
        },
        "v1alpha1.ApplicationSourcePlugin": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.EnvEntry"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.ApplicationSourcePluginParameter"
                    }
                }
            }
        },
        "v1alpha1.ApplicationSourcePluginParameter": {
            "type": "object",
            "properties": {
                "array": {
                    "description": "Array is the value of an array type parameter.\n+optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "map": {
                    "description": "Map is the value of a map type parameter.\n+optional",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "Name is the name identifying a parameter.",
                    "type": "string"
                },
                "string": {
                    "description": "String_ is the value of a string type parameter.",
                    "type": "string"
                }
            }
        },
        "v1alpha1.ComparedTo": {
            "type": "object",
            "properties": {
                "destination": {
                    "description": "Destination is a reference to the application's destination used for comparison",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationDestination"
                        }
                    ]
                },
                "ignoreDifferences": {
                    "description": "IgnoreDifferences is a reference to the application's ignored differences used for comparison",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.ResourceIgnoreDifferences"
                    }
                },
                "source": {
                    "description": "Source is a reference to the application's source used for comparison",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSource"
                        }
                    ]
                },
                "sources": {
                    "description": "Sources is a reference to the application's multiple sources used for comparison",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.ApplicationSource"
                    }
                }
            }
        },
        "v1alpha1.EnvEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name is the name of the variable, usually expressed in uppercase",
                    "type": "string"
                },
                "value": {
                    "description": "Value is the value of the variable",
                    "type": "string"
                }
            }
        },
        "v1alpha1.HelmFileParameter": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name is the name of the Helm parameter",
                    "type": "string"
                },
                "path": {
                    "description": "Path is the path to the file containing the values for the Helm parameter",
                    "type": "string"
                }
            }
        },
        "v1alpha1.HelmParameter": {
            "type": "object",
            "properties": {
                "forceString": {
                    "description": "ForceString determines whether to tell Helm to interpret booleans and numbers as strings",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is the name of the Helm parameter",
                    "type": "string"
                },
                "value": {
                    "description": "Value is the value for the Helm parameter",
                    "type": "string"
                }
            }
        },
        "v1alpha1.JsonnetVar": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.KustomizePatch": {
            "type": "object",
            "properties": {
                "options": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "patch": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "target": {
                    "$ref": "#/definitions/v1alpha1.KustomizeSelector"
                }
            }
        },
        "v1alpha1.KustomizeReplica": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Number of replicas",
                    "allOf": [
                        {
                            "$ref": "#/definitions/intstr.IntOrString"
                        }
                    ]
                },
                "name": {
                    "description": "Name of Deployment or StatefulSet",
                    "type": "string"
                }
            }
        },
        "v1alpha1.KustomizeSelector": {
            "type": "object",
            "properties": {
                "annotationSelector": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "labelSelector": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.ResourceIgnoreDifferences": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "jqPathExpressions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "jsonPointers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "managedFieldsManagers": {
                    "description": "ManagedFieldsManagers is a list of trusted managers. Fields mutated by those managers will take precedence over the\ndesired state defined in the SCM and won't be displayed in diffs",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "v1alpha1.SyncStatus": {
            "type": "object",
            "properties": {
                "comparedTo": {
                    "description": "ComparedTo contains information about what has been compared",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ComparedTo"
                        }
                    ]
                },
                "revision": {
                    "description": "Revision contains information about the revision the comparison has been performed to",
                    "type": "string"
                },
                "revisions": {
                    "description": "Revisions contains information about the revisions of multiple sources the comparison has been performed to",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "Status is the sync state of the comparison",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.SyncStatusCode"
                        }
                    ]
                }
            }
        },
        "v1alpha1.SyncStatusCode": {
            "type": "string",
            "enum": [
                "Unknown",
                "Synced",
                "OutOfSync"
            ],
            "x-enum-varnames": [
                "SyncStatusCodeUnknown",
                "SyncStatusCodeSynced",
                "SyncStatusCodeOutOfSync"
            ]
        },
        "view.AppView": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "description": "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources\n+optional",
                    "type": "string"
                },
                "kind": {
                    "description": "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds\n+optional",
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/view.ObjectMeta"
                },
                "operation": {
                    "$ref": "#/definitions/v1.Operation"
                },
                "spec": {
                    "$ref": "#/definitions/view.ApplicationSpec"
                },
                "status": {
                    "$ref": "#/definitions/view.ApplicationStatus"
                }
            }
        },
        "view.Application": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/view.AppView"
                },
                "codeAZ": {
                    "type": "string"
                },
                "eid": {
                    "description": "effective ID",
                    "type": "string"
                },
                "gitops": {
                    "type": "string"
                },
                "id": {
                    "description": "local ID",
                    "type": "string"
                },
                "resourceName": {
                    "description": "human-readable name",
                    "type": "string"
                },
                "resourceTypeId": {
                    "type": "string"
                }
            }
        },
        "view.ApplicationSource": {
            "type": "object",
            "properties": {
                "chart": {
                    "description": "Chart is a Helm chart name, and must be specified for applications sourced from a Helm repo.",
                    "type": "string"
                },
                "helm": {
                    "description": "Helm holds helm specific options",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSourceHelm"
                        }
                    ]
                },
                "name": {
                    "description": "Name is used to refer to a source and is displayed in the UI. It is used in multi-source Applications.",
                    "type": "string"
                },
                "path": {
                    "description": "Path is a directory path within the Git repository, and is only valid for applications sourced from Git.",
                    "type": "string"
                },
                "plugin": {
                    "description": "Plugin holds config management plugin specific options",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.ApplicationSourcePlugin"
                        }
                    ]
                },
                "ref": {
                    "description": "Ref is reference to another source within sources field. This field will not be used if used with a ` + "`" + `source` + "`" + ` tag.",
                    "type": "string"
                },
                "repoURL": {
                    "description": "RepoURL is the URL to the repository (Git or Helm) that contains the application manifests",
                    "type": "string"
                },
                "targetRevision": {
                    "description": "TargetRevision defines the revision of the source to sync the application to.\nIn case of Git, this can be commit, tag, or branch. If omitted, will equal to HEAD.\nIn case of Helm, this is a semver tag for the Chart's version.",
                    "type": "string"
                }
            }
        },
        "view.ApplicationSpec": {
            "type": "object",
            "properties": {
                "source": {
                    "description": "Source is a reference to the location of the application's manifests or chart",
                    "allOf": [
                        {
                            "$ref": "#/definitions/view.ApplicationSource"
                        }
                    ]
                }
            }
        },
        "view.ApplicationStatus": {
            "type": "object",
            "properties": {
                "conditions": {
                    "description": "Conditions is a list of currently observed application conditions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.ApplicationCondition"
                    }
                },
                "health": {
                    "description": "Health contains information about the application's current health status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.AppHealthStatus"
                        }
                    ]
                },
                "resources": {
                    "description": "Resources is a list of Kubernetes resources managed by this application",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ResourceStatus"
                    }
                },
                "sync": {
                    "description": "Sync contains information about the application's current sync status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1alpha1.SyncStatus"
                        }
                    ]
                }
            }
        },
        "view.ObjectMeta": {
            "type": "object",
            "properties": {
                "creationTimestamp": {
                    "type": "string"
                },
                "generateName": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "ownerReferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.OwnerReference"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Auth Token to have access to Argo Ctrl. \"Bearer [Auth Token]\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "scopes": {
                "organizationbillingread": "Grants read access to organization billing",
                "organizationbillingwrite": "Grants write access to organization billing",
                "organizationiamread": "Grants read access to organization IAM",
                "organizationiamwrite": "Grants write access to organization IAM",
                "organizationprojectmanagement": "Grants project management access in organization",
                "organizationread": "Grants read access to organization",
                "organizationwrite": "Grants write access to organization",
                "projectdiskread": "Grants read access to Disk in project",
                "projectdiskwrite": "Grants write access to Disk in project",
                "projecteipread": "Grants read access to EIP in project",
                "projecteipwrite": "Grants write access to EIP in project",
                "projectinstancecontrol": "Grants control (start, stop) access to instance in project",
                "projectinstanceread": "Grants read access to instance in project",
                "projectinstanceterminal": "Grants terminal access to instance in project",
                "projectinstancewrite": "Grants write access to instance in project",
                "projectlbread": "Grants read access to LoadBalancer in project",
                "projectlbwrite": "Grants write access to LoadBalancer in project",
                "projectsnapshotread": "Grants read access to Snapshot and Instance Snapshot in project",
                "projectsnapshotwrite": "Grants write access to Snapshot and Instance Snapshot in project",
                "projectsshread": "Grants read access to SSH in project",
                "projectsshwrite": "Grants write access to SSH in project",
                "projectsubnetread": "Grants read access to Subnet in project",
                "projectsubnetwrite": "Grants write access to Subnet in project",
                "projectvpcread": "Grants read access to VPC in project",
                "projectvpcwrite": "Grants write access to VPC in project"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SPX Argo Controller",
	Description:      "SPX Argo Controller HTTP API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
