{{- range .Values.clusters }}
{{- if .rgwAdminOps }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rgw-admin-ops-user
  namespace: {{ .name }}
type: kubernetes.io/rook
stringData:
  accessKey: {{ .rgwAdminOps.accessKey | quote }}
  secretKey: {{ .rgwAdminOps.secretKey | quote }}
{{- end }}
{{- end }}
