{{- range .Values.clusters }}
{{- $cluster := .name }}
{{- range .objectStores }}
{{- if and .tls .tls.enabled .tls.cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s.%s-tls" $cluster .name }}
  namespace: {{ $cluster }}
stringData:
  cert: {{ .tls.cert | quote }}
{{- end }}
{{- end }}
{{- end }}
