apiVersion: v2
name: superphenix-management
description: A Helm chart for Superphenix management components
type: application
# This chart inherits the tag of the Git repository
version: 0.0.0
appVersion: "0.0.0"
# Removed to temporarily satisfy CICD
dependencies:
#  - name: superphenix-console
#    version: 0.0.0
#    repository: "oci://ghcr.io/super-phenix/charts"
#    condition: superphenix-console.enabled
  - name: talos-operator
    version: 0.6.1
    repository: "https://alperencelik.github.io/helm-charts"
    condition: talos-operator.enabled
