# -- Superphenix Console configuration
superphenix-console:
  enabled: true

# -- Talos Operator configuration
talos-operator:
  enabled: false
  featureFlags:
    enablePxeBootStack: true

# -- iDRAC Exporter configuration
idrac-exporter:
  enabled: false