{{- range .Values.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
stringData:
  userID: {{ .username | quote }}
  userKey: {{ .token | quote }}
{{- end }}