{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "superphenix-controller.fullname" . }}-webhook-cert
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "superphenix-controller.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "superphenix-controller.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "superphenix-controller.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.webhook.certManager.issuerRef.kind | default "Issuer" }}
    name: {{ .Values.webhook.certManager.issuerRef.name | default (printf "%s-webhook-issuer" (include "superphenix-controller.fullname" .)) }}
  secretName: {{ include "superphenix-controller.fullname" . }}-webhook-cert
{{- end }}
