{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled (not .Values.webhook.certManager.issuerRef.name) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "superphenix-controller.fullname" . }}-webhook-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "superphenix-controller.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
