## Append samples of your project ##
resources:
- operator_v1alpha1_cluster.yaml
- operator_v1alpha1_organization.yaml
- operator_v1alpha1_project.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
