package view

import (
	"fmt"

	"github.com/super-phenix/superphenix/internal/superphenix-controller/internal/utils"

	spxId "github.com/super-phenix/superphenix/pkg/superphenix-id"

	v1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	k8smetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

type VPCView struct {
	k8smetav1.TypeMeta `json:",inline"`
	ObjectMeta         `json:"metadata,omitempty"`

	Spec   VPCSpec   `json:"spec"`
	Status VPCStatus `json:"status,omitempty"`
}

type VPCSpec struct {
	StaticRoutes []StaticRoute `json:"staticRoutes,omitempty"`
}

type StaticRoute struct {
	Policy        v1.RoutePolicy `json:"policy,omitempty"`
	CIDR          string         `json:"cidr"`
	NextHopIP     string         `json:"nextHopIP"`
	RouteTable    string         `json:"routeTable"`
	AutoGenerated bool           `json:"autoGenerated,omitempty"`
	IsOverriden   bool           `json:"isOverriden,omitempty"`
}

type VPCStatus struct {
	// Conditions represents the latest state of the object
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []v1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`

	Subnets []string `json:"subnets"`
}

func UnstructuredVPCToView(vpc *unstructured.Unstructured) VPCView {
	var view VPCView
	if err := utils.UnstructuredToStruct(vpc, &view); err != nil {
		return VPCView{}
	}
	view.Labels = utils.FilterLabels(view.Labels)
	view.Annotations = utils.FilterAnnotations(view.Annotations)
	return view
}

func VPCToView(vpc v1.Vpc, natGwStaticRoutes map[string]StaticRoute) VPCView {
	vpc.Labels = utils.FilterLabels(vpc.GetLabels())
	vpc.Annotations = utils.FilterAnnotations(vpc.GetAnnotations())

	// Parse every route to specify AutoGenerated
	srList := make([]StaticRoute, 0)
	for _, vpcSr := range vpc.Spec.StaticRoutes {
		sr := StaticRoute{
			Policy:     vpcSr.Policy,
			CIDR:       vpcSr.CIDR,
			NextHopIP:  vpcSr.NextHopIP,
			RouteTable: vpcSr.RouteTable,
		}
		key := fmt.Sprintf("%s-%s-%s", sr.Policy, sr.CIDR, sr.RouteTable)
		// If there is a matching natGw Static Route
		if v, ok := natGwStaticRoutes[key]; ok {
			// If same LanIP then the route is auto generated
			// Else it has an override, just treat it as a standard route
			if v.NextHopIP == sr.NextHopIP {
				sr.AutoGenerated = true
			}
		}
		srList = append(srList, sr)
	}

	view := VPCView{
		TypeMeta: vpc.TypeMeta,
		ObjectMeta: ObjectMeta{
			Name:              vpc.Name,
			GenerateName:      vpc.GenerateName,
			Namespace:         vpc.Namespace,
			CreationTimestamp: vpc.CreationTimestamp,
			Labels:            vpc.Labels,
			OwnerReferences:   vpc.OwnerReferences,
		},
		Spec: VPCSpec{
			StaticRoutes: srList,
		},
		Status: VPCStatus{
			Conditions: vpc.Status.Conditions,
			Subnets:    vpc.Status.Subnets,
		},
	}
	return view
}

func VPCToResource(vpcView VPCView) VPC {
	return VPC{
		Resource: Resource{
			ID:          vpcView.Labels[spxId.SpxLabelResourceLocalID],
			EId:         vpcView.Name,
			ProductName: vpcView.Labels[spxId.SpxLabelResourceName],
			Gitops:      vpcView.Labels[spxId.SpxLabelGitops],
		},
		VPC: vpcView,
	}
}
