#  # -- AZ in which the datastores are deployed
location: ""

# -- Defines default values for datastores
# @section -- Datastore default parameters
dataStoreDefaults:
  replicas: 3
  storage: 10Gi

# -- Defines datastore resources for the controlplanes.
# Each key defines a datastore and should be unique
# See values.yaml for the complete syntax.
# @default -- {}
dataStores: {}
  # fr01-abc01-virt01-datastore01:
  #   # Storage class friendly name to use
  #   # @section -- Datastore
  #   storageClassName: ""
  #
  #   # -- Size of the persistentVolumeClaims
  #   # @section -- Datastore
  #   storage: 10Gi
  #
  #   # -- Version tag of the etcd image
  #   # @section -- Datastore
  #   version: 3.6.7
  #
  #   # -- Datastore backups configuration
  #   # @section -- Backups
  #   backups:
  #     # -- Whether backups are enabled
  #     enabled: true
  #
  #     # -- Whether the backup schedule is paused
  #     paused: false
  #
  #     # -- CRON schedule to run the backups at intervals
  #     schedule: "30 1 * * *"
  #
  #     retention:
  #       # -- Retention time of the backups in hours (max is 960, or 40 days)
  #       expiryTime: 720
