package objectbucket

import (
	"context"

	"github.com/super-phenix/superphenix/internal/superphenix-controller/internal/utils"
	"github.com/super-phenix/superphenix/internal/superphenix-controller/pkg/config"
	logger "github.com/super-phenix/superphenix/pkg/utils/log"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Credentials is the S3 connection information generated by the provisioner
// for the per-bucket admin user.
type Credentials struct {
	Endpoint        string `json:"endpoint"`
	BucketName      string `json:"bucketName"`
	Region          string `json:"region,omitempty"`
	AccessKeyID     string `json:"accessKeyId"`
	SecretAccessKey string `json:"secretAccessKey"`
}

// GetCredentials reads the S3 endpoint from the bound ObjectBucket and the
// access keys from the Secret the provisioner created alongside the OBC. The
// Secret shares the OBC's name and carries no SPX labels, so ownership is
// checked on the OBC itself first.
func GetCredentials(ctx context.Context, namespace, effectiveId string) (Credentials, error) {
	log := logger.GetLogger(ctx)

	obc, err := config.DynamicClientSet.Resource(ObjectBucketClaimGVR).Namespace(namespace).Get(ctx, NamePrefix+effectiveId, metav1.GetOptions{})
	if err != nil {
		return Credentials{}, err
	}
	if err := utils.CheckProjectLabel(obc, namespace); err != nil {
		return Credentials{}, err
	}

	name := NamePrefix + effectiveId
	secret, err := config.K8sClient.CoreV1().Secrets(namespace).Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		log.Err(err).Str("namespace", namespace).Str("name", name).Msg("Failed to get bucket Secret")
		return Credentials{}, err
	}

	ob := resolveOBEndpoint(ctx, obc)
	bucketName := ob.BucketName
	if bucketName == "" {
		bucketName = effectiveId
	}

	return Credentials{
		Endpoint:        endpointOrFallback(ob.Endpoint),
		BucketName:      bucketName,
		Region:          ob.Region,
		AccessKeyID:     string(secret.Data["AWS_ACCESS_KEY_ID"]),
		SecretAccessKey: string(secret.Data["AWS_SECRET_ACCESS_KEY"]),
	}, nil
}
