{{- if .Values.global.project.gitops.valuesLocation.repoURL }}
apiVersion: v1
kind: Secret
metadata:
  name: repository-{{ .Values.global.project.projectID }}
  labels:
    {{- include "self-service-projects.labels" . | nindent 4 }}
    argocd.argoproj.io/secret-type: repository
stringData:
  name: "repository-{{ .Values.global.project.projectID }}"

  url: {{ .Values.global.project.gitops.valuesLocation.repoURL | quote }}

  {{- with .Values.global.project.gitops.valuesLocation.credentials.username }}
  username: {{ . | quote }}
  {{- end }}

  {{- with .Values.global.project.gitops.valuesLocation.credentials.password }}
  password: {{ . | quote }}
  {{- end }}

  {{- with .Values.global.project.gitops.valuesLocation.credentials.insecure }}
  insecure: {{ . | quote }}
  {{- end }}

  {{- with .Values.global.project.gitops.valuesLocation.credentials.forceHttpBasicAuth }}
  forceHttpBasicAuth: {{ . | quote }}
  {{- end }}

  {{- with .Values.global.project.gitops.valuesLocation.credentials.enableLfs }}
  enableLfs: {{ . | quote }}
  {{- end }}

  {{- with .Values.global.project.gitops.valuesLocation.credentials.sshPrivateKey }}
  sshPrivateKey: | 
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
