# -- Specification of the target cluster
# These parameters cannot be overriden by the user.
cluster:
  # -- SPXID
  clusterID: ""
  friendlyName: ""
  # -- Console clusters: random uuidv4 -- Gitops clusters: friendly name
  name: ""
  kubeVersion: ""

controlPlane:
  fqdn: ""
  network:
    apiServer:
      address: 10.96.0.1
      konnectivityPort: 7442
      port: 7443
      proxyPort: 7444

kubevirtCsi:
  # https://kubernetes.io/docs/concepts/storage/storage-classes/
  storageClasses: {}
    # default:
    #   isDefaultClass: true
    #   tenantClass: default
    #   infraClass: default
    #   reclaimPolicy: Delete
    #   allowVolumeExpansion: true
  # https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/
  snapshotclasses: {}
    # default:
    #   isDefaultClass: true
    #   tenantClass: default
    #   infraClass: default
    #   deletionPolicy: Delete
  
  versions:
    # https://github.com/kubernetes-csi/node-driver-registrar/releases
    # https://github.com/kubernetes-csi/livenessprobe/releases
    # https://github.com/kubernetes-csi/external-snapshotter/releases
    # https://quay.io/repository/kubevirt/kubevirt-csi-driver?tab=tags
    v1.35:
      nodeDriverRegistrarVersion: v2.16.0
      csiLivenessprobeVersion: v2.18.0
      snapshotControllerVersion: v8.5.0
      csiDriverVersion: latest
    v1.36:
      nodeDriverRegistrarVersion: v2.17.0
      csiLivenessprobeVersion: v2.19.0
      snapshotControllerVersion: v8.6.0
      csiDriverVersion: latest

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %          Metrics server           %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
metrics-server:
  fullnameOverride: "metrics-server"
  args:
    - --kubelet-insecure-tls=true
    - --kubelet-preferred-address-types=InternalIP
  apiService:
    create: true

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %              Cilium               %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cilium:
  kubeProxyReplacement: true
  ipam:
    mode: kubernetes
  k8s:
    requireIPv4PodCIDR: true
  securityContext:
    privileged: false
  cni:
    chainingMode: portmap
  sessionAffinity: true
  k8sServiceHost: ""
  k8sServicePort: 7443

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %              CoreDNS              %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
coredns:
  # Initial amount of DNS instances
  replicaCount: 2

  k8sAppLabelOverride: "kube-dns"
  deployment:
    name: coredns

  service:
    name: "kube-dns"
    # IP of the DNS cluster-wide
    clusterIP: "10.96.0.10"

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                k8s-app: kube-dns
            topologyKey: kubernetes.io/hostname
          weight: 1
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
